sudo: false

language: java


jdk:
  - oraclejdk8

addons:
  apt:
    sources:
      - mongodb-upstart
      - mongodb-3.2-precise
    packages:
      - oracle-java8-installer
      - mongodb-org-server
      - mongodb-org-shell

install: ./gradlew assemble

before_script:
  - sleep 15

script: ./gradlew externalCiTest

after_success:
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-data-model:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-messaging:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-processing-model:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-api:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-repository:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-progress-monitor:uploadArchives
  - test $TRAVIS_BRANCH = "master" && ./gradlew subs-dispatcher:uploadArchives


before_install:
- openssl aes-256-cbc -K $encrypted_d65fefe7827f_key -iv $encrypted_d65fefe7827f_iv
  -in gradle_props.tar.enc -out gradle_props.tar -d
- tar xvf gradle_props.tar

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  apt: true
  directories:
    - $HOME/.m2
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
