services:
  - rabbitmq

addons:
  apt:
    sources:
      - mongodb-upstart
    packages:
      - mongodb-org-server

sudo: required

language: java

jdk:
  - oraclejdk8

install: true

before_script:
  - mongo --vesion

script: ./gradlew check

after_success:
- ./gradlew cobertura coveralls
- ./gradlew subs-data-model:uploadArchives
- ./gradlew subs-messaging:uploadArchives
- ./gradlew subs-processing-model:uploadArchives

before_install:
- openssl aes-256-cbc -K $encrypted_d65fefe7827f_key -iv $encrypted_d65fefe7827f_iv
  -in gradle_props.tar.enc -out gradle_props.tar -d
- tar xvf gradle_props.tar
